config/routes.rb
Rails.application.routes.draw do
  get 'charges/create'

  get 'charges/new'

  resources :charges

post 'order_complete' => 'cart#order_complete'
post 'add_to_cart' => 'cart#add_to_cart'

  get 'view_order' =>'cart#view_order'

  get 'checkout' =>'cart#checkout'

  devise_for :users
  root 'storefront#all_items'

  get 'categorical' => 'storefront#items_by_category' 

  get 'branding' => 'storefront#items_by_brand'
  
  get 'admin' => 'products#index'
  resources :products

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end


        if user.admin?
            can :manage, Product
        elsif user.guest?
            can :show, Product
        end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/category.rb
class Category < ActiveRecord::Base

	has_many :products
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base

	belongs_to :product
	belongs_to :order
end

app/models/order.rb
class Order < ActiveRecord::Base

	has_many :line_items
	belongs_to :user

	serialize :order_items, Hash
end

app/models/product.rb
class Product < ActiveRecord::Base

	mount_uploader :image, ImageUploader
	belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders


  def admin?
    role == 'admin'
  end	

  def guest?
    role == 'guest'
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  before_filter :categories, :brands
  helper_method :current_order

  def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:role])
   devise_parameter_sanitizer.permit(:account_update, keys[:role])
  end

 #Fills the dropdown for our category link on the navbar
  def categories
  	@categories = Category.all
  end

  def brands
  	@brands =  Product.pluck(:brand).sort.uniq
  end	

  def current_order
    if !session[:order_id].nil?
      Order.find(session[:order_id])
    else
      Order.new
    end
  end
  	
end

app/controllers/cart_controller.rb
class CartController < ApplicationController

	before_filter :authenticate_user!, except:[:add_to_cart, :view_order]


  def add_to_cart
  	@order = current_order

    line_item = @order.line_items.new(product_id: params[:product_id], quantity: params[:quantity])
    @order.save
    session[:order_id] = @order.id

    line_item.update(line_item_total: (line_item.product.price * line_item.quantity))

    redirect_to :back
  end

  def view_order
  	@line_items = current_order.line_items
  end

  def checkout

  line_items = current_order.line_items

    if line_items.length != 0
        current_order.update(user_id: current_user.id, subtotal: 0)

	@order = current_order

	line_items.each do |line_item|
  	    line_item.product.update(quantity: (line_item.product.quantity - line_item.quantity))
  	    @order.order_items[line_item.product_id] = line_item.quantity 
  	    @order.subtotal += line_item.line_item_total
  	end
	@order.save

  	@order.update(sales_tax: (@order.subtotal * 0.08))
  	@order.update(grand_total: (@order.sales_tax + @order.subtotal))

        @order.line_items.destroy_all

        session[:order_id] = nil
    end
  end


  def order_complete

  	 @order = Order.find(params[:order_id])
    @amount = (@order.grand_total.to_f.round(2) * 100).to_i

    customer = Stripe::Customer.create(
      :email => current_user.email,
      :card => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer => customer.id,
      :amount => @amount,
      :description => 'Rails Stripe customer',
      :currency => 'usd'
    )

    rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to cart_path

  end	
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def create
  	# this action is what actually performs the transaction.

		# Amount in cents
		@amount = 500

		customer = Stripe::Customer.create(
			:email => 'example@stripe.com',
			:card => params[:stripeToken]
		)

		charge = Stripe::Charge.create(
			:customer => customer.id,
			:amount => @amount,
			:description => 'Rails Stripe customer',
			:currency => 'usd'
		)

		rescue Stripe::CardError => e
		flash[:error] = e.message
		

  end

  def new
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  before_filter :authenticate_user!, except: [:show]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
    @categories = Category.all
  end

  # GET /products/1/edit
  def edit
    @categories = Category.all
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :quantity, :description, :brand, :rating, :category_id, :image, :price)
    end
end

app/controllers/storefront_controller.rb
class StorefrontController < ApplicationController
  def all_items
  	@products = Product.all
  
  end

  def items_by_category

  	@products = Product.where(category_id: params[:category_id])
  	@category = Category.find(params[:category_id])
  
  end

  def items_by_brand
  	@products = Product.where(brand: params[:brand])
  	@brand = params[:brand]

  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/storefront_helper.rb
module StorefrontHelper
end

app/views/cart/add_to_cart.html.erb
<h1>Cart#add_to_cart</h1>
<p>Find me in app/views/cart/add_to_cart.html.erb</p>

app/views/cart/checkout.html.erb
<h2>Thanks for shopping with us!</h2>
<p>Let's review your order:</p>

<% @order.order_items.each do |k,v| %>
    <ul>
        <li><%= Product.find(k).name %></li>
        <li>Quantity Purchased:<%= v %>
    </ul>
<% end %>

<p>
    <strong>Subtotal:</strong> <%= number_to_currency @order.subtotal %>
</p>
<p>
    <strong>Sales Tax:</strong> <%= number_to_currency @order.sales_tax %>
</p>

<p>
    <strong>Order Total:</strong> <%= number_to_currency @order.grand_total %>
</p>

<div>
	<%= form_tag order_complete_path do %>
		<article>
			<label class="amount">
				<span><%= number_to_currency @order.grand_total %></span>
			</label>
		</article>
		<div>
			<%= hidden_field_tag :order_id, @order.id %>
		</div>

		<script src="http://checkout.stripe.com/checkout.js"
		class="stripe-button"
		data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
		data-description="Order #<%= @order.id %>"
		data-amount="<%= (@order.grand_total.to_f.round(2) * 100) %>"></script>
	<% end %>
</div>

app/views/cart/order_complete.html.erb
<h2>Your order is complete! Thank you for shopping with us! </h2>

<h3>
<p> Your order <strong><%= @order.id %> will be shipping to you soon!</strong></p>

<p>Again, thank you <%= @order.user.email %> for shopping with us.  Stop by again for some amazing deals!</p>
</h3>

app/views/cart/view_order.html.erb
<h2>My Cart</h2>
<% cart_total = 0 %>
<div>
  <% @line_items.each do |line_item| %>
    <li><%= line_item.product.name %></li>
    <li><%= number_to_currency line_item.product.price %></li>
    <li>Qty: <%= line_item.quantity %></li>
    <li>Subtotal: <%= line_item.line_item_total %></li>

    <% cart_total  += line_item.line_item_total %>
  <% end %>
</div>

	<h3>Cart total: <%= number_to_currency cart_total %></h3>

<div>
  <%= link_to "Proceed to Checkout?", checkout_path, class: "btn btn-success" %>
</div>

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2

app/views/charges/new.html.erb
<div>
    <%= form_tag charges_path do %>
    
        <article>
            <label class="amount">
                <span>Amount: $5.00</span>
            </label>
        </article>
    
        <script src="https://checkout.stripe.com/checkout.js" 
         class="stripe-button" 
         data-key="<%=Rails.configuration.stripe[:publishable_key] %>" 
         data-description="A month's subscription" 
         data-amount="500"></script>
    
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Spr17Amazon</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
    </div>
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav nav-tabs">
         		<li><%= link_to "Home", root_path %></li>
          <% if user_signed_in? %>
	           <li><%= link_to "Edit Profile", edit_user_registration_path %></li> 
	           <li> <%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>

              <% if current_user.role == "admin" %>
                <li><%= link_to "Admin", admin_path %></li>
              <% end %>  



	        <% else %>
	         		 <li><%= link_to "Sign in ", new_user_session_path %></li> 	
          <% end %>




          <li class="dropdown">
    				<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
	        	<ul class="dropdown-menu">
		    			<% @categories.each do |category| %>
	                  <li><%= link_to category.name, categorical_path(category_id: category.id)%></li>
	            <% end %>
	        	</ul>
     			</li>

     			<!-- Brands -->
					<li class="dropdown">
					  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Brands<span class="caret"></span></a>
					  <ul class="dropdown-menu">
					    <% @brands.each do |brand| %>
					      <li><%= link_to brand, branding_path(brand: brand) %></li>
					    <% end %>
					      <li><%= link_to 'All', root_path %></li>
					  </ul>
					</li> 
					<!-- End Brands --> 
          <li><%= link_to "View Cart", view_order_path %></li>  
   
      </ul>

      <h3 class="nav-title"><%= image_tag "shopping-cart.png" %>Crayton Co.</h3>
     
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


<div class='container'>
	<%= yield %>
</div>
</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="form-group">
    <%= f.label :price %><br>
    <%= f.number_field :price%>
  </div>

  <div class="form-group">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="form-group">
    <%= f.label :brand %><br>
    <%= f.text_field :brand %>
  </div>
  
  <div class="form-group">
    
    <%= f.select(:category_id, @categories.collect {|c| [c.name, c.id]},{include_blank: "Please select a category"}) %>
  </div>
  <div class="form-group">
  <strong>Upload an Image:</strong>
    <%= f.file_field :image %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Description</th>
      <th>Brand</th>
      <th>Rating</th>
      <th>Category</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= number_to_currency product.price %></td>
        <td><%= product.quantity %></td>
        <td><%= product.description %></td>
        <td><%= product.brand %></td>
        <td><%= product.rating %></td>
        <td><%= product.category_id %></td>
        <td><%= image_tag product.image.thumb %></td>
        <td><%= link_to 'Show', product %></td>
        <% if can? :update, product %>
          <td><%= link_to 'Edit', edit_product_path(product) %></td>
          <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if can? :create, Product %>
  <%= link_to 'New Product', new_product_path %>
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency @product.price %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @product.quantity %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @product.brand %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @product.rating %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category_id %>
</p>

<p>
<%= image_tag @product.image.url %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/storefront/_productdisplay.html.erb
<div class="row">
	<% @products.each do |product| %>
		<div class="col-md-6">
			<div class="well center-it">
				<p><%= image_tag product.image.thumb %></p>
				<h3><%= link_to product.name, product %></h3>
				<p><%= number_to_currency product.price %></p>

				<p>
					<a href="#" data-toggle="modal" data-target="#myModal_<%= product.id %>" ><span class="glyphicon glyphicon-plus">

					</span>Quick Info
					</a>
				</p>
				<p>Made By <strong><%=product.brand %></strong></p>
			</div>
		</div>

		<!-- Modal -->
    <div class="modal fade" id="myModal_<%=product.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel"><%= product.name %></h4>
          </div>
          <div class="modal-body">
          	<p><%= image_tag product.image.url, style: "width:250px; height:200px;" %></p>
            <h2><%= product.description %></h2>
            <h4><%= number_to_currency product.price %></h4>
            <h4>We have <%=product.quantity %> in stock!</h4>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <p>
              <%= form_tag add_to_cart_path do %>
                <%= hidden_field_tag :product_id, product.id %>
                <%= number_field_tag :quantity, nil, placeholder: "How many?" %>
                <%= submit_tag "Add to Cart", class: "btn btn-primary" %>
              <% end %>
            </p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/storefront/all_items.html.erb
<div class="center-it">
	<h1>Welcome to Crayton Co!</h1>
<h3>We have what you want!</h3>
</div>


<%= render 'productdisplay' %>




	

app/views/storefront/items_by_brand.html.erb
<div class="center-it">
	<h1>Welcome to Crayton Co!</h1>
<h3>We have what you want!</h3>
</div>

<h1>Here are our <%= @brand %> products</h1>

<%= render 'productdisplay' %>

app/views/storefront/items_by_category.html.erb
<div class="center-it">
	<h1>Welcome to Crayton Co!</h1>
<h3>We have what you want!</h3>
</div>

<h1>All of our <%= @category.name %> products</h1>

<%= render 'productdisplay' %>